### ISSUE TITLE
ValueError: Input y contains NaN

### ISSUE THREAD

**Issue by Re-dot-art** [Manuelfjr/birt-gd#13]
I encountered an error while running **the sample code** shown in your article, which shows that **input y contains nan**. How can I solve this problem?
![1](https://user-images.githubusercontent.com/93500522/230566662-c19b8bc2-3ea4-4e2f-8301-007d9d18ad01.jpg)
![2](https://user-images.githubusercontent.com/93500522/230566682-35c97382-240c-4299-bb9e-33905ffbd2d8.jpg)
![3](https://user-images.githubusercontent.com/93500522/230566793-11f9ffba-2aa5-4dd2-8b14-4dfc85c01575.jpg)

**Comment by Manuelfjr** [comment]
Recently, the model was introduced with the option of an initial guess, a prior information, and a parameter called set_priors for selecting whether to run with the prior information or not. To run the example, set `set_priors = False`.

This error occurred when all the responses from a respondent or an item were the same. In this case, when calculating the prior information using correlation, it results in "nan" because the variance is undefined.
